from __future__ import annotations

from copy import deepcopy


DEMO_SNAPSHOT_SCHEMA_VERSION = "competition-offline-demo/v1"
DEMO_SOURCE = "fully_desensitized_fictional"


def build_fully_desensitized_demo_snapshot() -> dict:
    """Return deterministic fictional data for a network-free competition demo."""
    project_id = "demo-project-2026-a"
    finding_id = "demo-finding-a-b"
    bidder_a, bidder_b, bidder_c = "投标人示例甲", "投标人示例乙", "投标人示例丙"
    record_ids = ["demo-record-001", "demo-record-002", "demo-record-003"]
    contributions = [
        {"contribution_id": "demo-contribution-network", "layer": "network", "signal_type": "shared_device", "strength": "strong", "score": 30, "source_feature_id": "demo-network-feature", "source_record_ids": record_ids[:2]},
        {"contribution_id": "demo-contribution-quote", "layer": "quote", "signal_type": "fixed_difference", "strength": "supporting", "score": 14, "source_feature_id": "demo-quote-feature", "source_record_ids": record_ids[1:]},
        {"contribution_id": "demo-contribution-cooccurrence", "layer": "cooccurrence", "signal_type": "stable_cooccurrence", "strength": "strong", "score": 22, "source_feature_id": "demo-cooccurrence-feature", "source_record_ids": record_ids},
    ]
    finding = {
        "finding_id": finding_id, "project_id": project_id, "document_id_a": "demo-doc-a", "document_id_b": "demo-doc-b",
        "bidder_a": bidder_a, "bidder_b": bidder_b, "anomaly_score": 58, "rule_score": 42,
        "model_score": 46, "model_threshold": 40, "model_triggered": True, "similarity": 0.71,
        "repeated_segment_count": 2, "repeated_segment_chars": 86,
        "evidence": ["示例文本存在可复核的重复表达片段。", "示例实体关联已脱敏，仅保留受控索引。"],
        "evidence_pages_a": [2], "evidence_pages_b": [3], "review_status": "pending_review",
    }
    analysis = {"ready": True, "summary": {"project_count": 3, "document_count": 6, "pair_count": 3, "anomaly_count": 1, "rule_anomaly_count": 1, "model_triggered_count": 1, "repeated_segment_evidence_count": 2, "comparable_project_count": 3}, "anomalies": [finding], "entities": [], "pairs": []}
    network = {"summary": {"record_count": 9, "project_count": 3, "bidder_count": 3, "expected_pair_count": 3, "completed_pair_count": 3, "triggered_pair_count": 1, "evidence_trace_rate": 1.0, "available_signal_types": ["shared_device", "upload_time_close"], "notice": "演示关联结果为完全虚构的脱敏线索，不展示设备或网络原值。"}, "features": [{"feature_id": "demo-network-feature", "project_id": project_id, "bidder_a_id": "demo-bidder-a", "bidder_b_id": "demo-bidder-b", "bidder_a_name": bidder_a, "bidder_b_name": bidder_b, "risk_score": 30, "risk_level": "medium", "review_status": "pending_review", "signals": [{"signal_type": "shared_device", "label": "共享设备标识（已脱敏）", "weight": 30}], "source_record_ids": record_ids[:2], "evidence_refs": [{"source_ref_id": "demo-source-ref-01"}] }], "graph": {"nodes": [], "edges": [], "projects": [project_id]}}
    quotes = {"summary": {"record_count": 9, "quote_record_count": 9, "project_count": 3, "bidder_count": 3, "expected_pair_count": 3, "completed_pair_count": 3, "triggered_pair_count": 1, "evidence_trace_rate": 1.0, "available_signal_types": ["fixed_difference", "pairwise_price_distance"], "notice": "演示报价模式为虚构数值结构，仅用于展示异常筛查流程。"}, "features": [{"feature_id": "demo-quote-feature", "project_id": project_id, "bidder_a_id": "demo-bidder-a", "bidder_b_id": "demo-bidder-b", "bidder_a_name": bidder_a, "bidder_b_name": bidder_b, "risk_score": 14, "risk_level": "low", "review_status": "pending_review", "risk_contributions": [{"signal_type": "fixed_difference", "label": "近似固定差额", "score": 14}], "source_record_ids": record_ids[1:], "evidence_refs": [{"source_ref_id": "demo-source-ref-02"}]}], "graph": {"nodes": [], "edges": [], "projects": [project_id]}}
    cooccurrence = {"summary": {"record_count": 9, "project_count": 3, "bidder_count": 3, "candidate_pair_count": 3, "triggered_pair_count": 1, "group_count": 1, "evidence_trace_rate": 1.0, "notice": "稳定共现仅作为待复核线索；单次共现和单一中标关系不能直接定性。"}, "features": [{"feature_id": "demo-cooccurrence-feature", "bidder_a_id": "demo-bidder-a", "bidder_b_id": "demo-bidder-b", "bidder_a_name": bidder_a, "bidder_b_name": bidder_b, "project_ids": [project_id, "demo-project-2026-b"], "risk_score": 38, "risk_level": "medium", "review_status": "pending_review", "risk_contributions": [{"signal_type": "stable_cooccurrence", "label": "稳定跨项目共现", "score": 22}], "evidence_refs": [{"source_ref_id": "demo-source-ref-03"}]}], "groups": [{"group_id": "demo-group-001", "group_type": "stable_multi_bidder_group", "bidder_ids": ["demo-bidder-a", "demo-bidder-b", "demo-bidder-c"], "bidder_names": [bidder_a, bidder_b, bidder_c], "stable_project_ids": [project_id, "demo-project-2026-b"], "stable_common_project_count": 2, "risk_score": 42}], "graph": {"nodes": [{"id": "demo-bidder-a", "type": "bidder", "label": bidder_a}, {"id": "demo-bidder-b", "type": "bidder", "label": bidder_b}, {"id": "demo-bidder-c", "type": "bidder", "label": bidder_c}], "edges": [{"id": "demo-global-edge", "type": "cooccurrence_anomaly", "source": "demo-bidder-a", "target": "demo-bidder-b", "risk_score": 38, "project_ids": [project_id, "demo-project-2026-b"]}]}}
    fusion = {"summary": {"schema_version": "bid-audit-risk-fusion/v1", "project_count": 3, "bidder_pair_count": 1, "group_count": 1, "document_count": 1, "high_risk_project_count": 1, "medium_risk_project_count": 0, "low_risk_project_count": 0, "evidence_event_count": 3, "notice": "演示风险分数仅用于全样本异常线索排序。高风险需同时满足强信号与独立维度佐证。"}, "projects": [{"entity_id": "demo-project-risk", "project_id": project_id, "risk_score": 70, "risk_level": "high", "review_status": "pending_review", "risk_contributions": contributions, "evidence_chain": {"summary": {"risk_level": "high", "risk_score": 70, "contribution_count": 3}, "calculation": {"rule": "strong_plus_independent_dimension", "independent_layers": ["network", "quote", "cooccurrence"]}, "source": {"evidence_event_ids": ["demo-evidence-01", "demo-evidence-02", "demo-evidence-03"], "source_record_ids": record_ids}}}], "bidder_pairs": [], "groups": [], "documents": [], "evidence_events": [{"event_id": "demo-evidence-01", "source_record_ids": record_ids}]}
    graph = {"schema_version": "evidence-graph/v1", "node_count": 4, "edge_count": 3, "project_count": 1, "projects": [project_id], "nodes": [{"id": "demo-project-node", "type": "project", "project_id": project_id, "label": "脱敏演示项目 A"}, {"id": "demo-project-bidder-a", "type": "bidder", "project_id": project_id, "label": bidder_a}, {"id": "demo-project-bidder-b", "type": "bidder", "project_id": project_id, "label": bidder_b}, {"id": "demo-entity", "type": "contact", "project_id": project_id, "label": "共同实体（已脱敏）"}], "edges": [{"source": "demo-project-bidder-a", "target": "demo-project-bidder-b", "type": "text_similarity", "project_id": project_id, "similarity": 0.71, "anomaly_score": 58, "finding_id": finding_id, "evidence": ["示例重复片段"]}, {"source": "demo-project-bidder-a", "target": "demo-entity", "type": "shared_entity", "project_id": project_id, "label": "共同实体"}, {"source": "demo-project-bidder-b", "target": "demo-entity", "type": "shared_entity", "project_id": project_id, "label": "共同实体"}], "findings": [finding], "warning": "离线演示图谱只含完全虚构、脱敏的占位信息。"}
    evidence = {"finding": deepcopy(finding), "document_a": {"document_id": "demo-doc-a", "page_number": 2}, "document_b": {"document_id": "demo-doc-b", "page_number": 3}, "pages_a": [{"document_id": "demo-doc-a", "page_number": 2, "file_path": "脱敏演示文件 A", "excerpt": "【虚构演示片段】此处仅展示可定位的脱敏文本摘要。"}], "pages_b": [{"document_id": "demo-doc-b", "page_number": 3, "file_path": "脱敏演示文件 B", "excerpt": "【虚构演示片段】此处仅展示另一份文件的脱敏文本摘要。"}], "warning": "这是完全脱敏、虚构的离线演示证据，不对应真实材料。"}
    coverage = {"source_files": {"discovered": 3, "recognized": 3}, "records": {"input_row_count": 9, "accepted_record_count": 9, "bidder_count": 3, "duplicate_record_count": 0}, "categories": {"files": {"record_count": 3, "usable_record_count": 3, "project_count": 3, "project_coverage_rate": 1.0, "available": True}, "quotes": {"record_count": 9, "usable_record_count": 9, "project_count": 3, "project_coverage_rate": 1.0, "available": True}, "ip": {"record_count": 0, "usable_record_count": 0, "project_count": 0, "project_coverage_rate": 0.0, "available": False}, "history": {"record_count": 6, "usable_record_count": 6, "project_count": 3, "project_coverage_rate": 1.0, "available": True}}, "data_quality": {"issue_count": 0, "severity_counts": {}, "missing_fields": {}}}
    return {"ready": True, "mode": "offline-demo", "schema_version": DEMO_SNAPSHOT_SCHEMA_VERSION, "source": DEMO_SOURCE, "fully_desensitized": True, "fictional": True, "title": "完全脱敏离线演示案例", "message": "已加载完全虚构、脱敏且预计算的离线演示快照；不会触发 OCR、训练、大模型或网络调用。", "metrics": {"archive_count": 3, "file_count": 9, "bid_document_count": 6, "page_count": 18, "gpu_ocr_document_count": 0, "comparable_project_count": 3, "pair_count": 3, "anomaly_count": 1}, "training": {"archive_count": 3, "file_count": 9}, "processed": {"success_count": 6, "page_count": 18}, "model": {"ready": True, "model": {"model_type": "frozen_unsupervised_demo"}, "summary": {"pair_count": 3, "label_status": "synthetic_demo_only"}}, "analysis": analysis, "network": network, "quotes": quotes, "cooccurrence": cooccurrence, "fusion": fusion, "coverage": coverage, "ingest": {"training": {"archive_count": 3, "file_count": 9}, "processed": {"success_count": 6, "page_count": 18}}, "graph": graph, "evidence_by_finding_id": {finding_id: evidence}}
